# Generated by Django 4.0.4 on 2022-06-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('age_months', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('status', models.CharField(choices=[('0', 'Sano'), ('1', 'En Pabellon'), ('2', 'En Observacion'), ('3', 'Otro')], max_length=1, verbose_name='Estado')),
                ('specie', models.CharField(max_length=50)),
                ('rut_owner', models.CharField(max_length=12)),
                ('description', models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
