# Generated by Django 4.0.4 on 2022-06-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinipet', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
